export default [
  {
    id: 1,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 2,
    price: "SAR 22.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 3,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 4,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 5,
    price: "SAR 44.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "90% off",
  },
  {
    id: 6,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 7,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 8,
    price: "SAR 44.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "90% off",
  },
  {
    id: 9,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 10,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
  {
    id: 11,
    price: "SAR 44.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "90% off",
  },
  {
    id: 12,
    price: "SAR 55.00",
    image: "https://fimgs.net/mdimg/perfume/375x500.53.jpg",
    text: "Lorem ipsum dolor sit amet, velit vitae nisl vitae",
    discount: "25% off",
  },
];
